[DOC-153] Add Exchange Technology Part B
Ed-Fi-Alliance-OSS/ed-fi-alliance-oss.github.io pull request #127
Opened 2024-12-14 03:03 UTC by roberthunterjr

Migrate Ed-Fi Exchange Technology portfolio part b items from Confluence to Docusaurus.

2024-12-17 17:45 UTC, stevenarnold-ed-fi requested changes

2024-12-17 17:45 UTC, stevenarnold-ed-fi commented on docs/getting-started/edfi-exchange/technology/the-north-allegheny-interventions-management-interface.md
> +![](https://edfi.atlassian.net/wiki/plugins/servlet/confluence/placeholder/unknown-macro?name=rate&locale=en_US&version=2)
@roberthunterjr delete this line - remnants of a macro from before the TechDocs cloud migration

2024-12-19 22:44 UTC, stephenfuqua commented on docs/getting-started/edfi-exchange/technology/quick-deploy-of-ed-fi-ods-api-development-server-using-on-premises-server.md
> +![MSDF Logo](https://edfidocs.blob.core.windows.net/$web/img/edfi-exchange/technology/msdflogo.png)
We need to shrink that image. Way too large and looks bad on my screen.

![image](https://github.com/user-attachments/assets/30480011-5817-4f08-9fe7-84cb7b51aaa9)

2024-12-19 22:44 UTC, stephenfuqua commented on docs/getting-started/edfi-exchange/technology/quick-deploy-of-ed-fi-ods-api-development-server-using-on-premises-server.md
> +* ****Code and Documentation:**** [https://github.com/Ed-Fi-Exchange-OSS/Ed-Fi-BinariesPowerShellInstaller](https://github.com/Ed-Fi-Exchange-OSS/Ed-Fi-BinariesPowerShellInstaller)
I was worried that the extra asterisk would cause a problem, but the display is fine. We can clean that up later (or never).

2024-12-19 22:44 UTC, stephenfuqua commented on docs/getting-started/edfi-exchange/technology/student-survey-dashboard-for-teachers.md
> +> View a 3 minute overview of the Buzz tool [here](https://vimeo.com/edfialliance/review/476016090/458295ac13).
We'll want to fix this, but it isn't a dealbreaker. Can merge without changing the admonition. We should search out any other overlooked admonitions during the cleanup process. I'll put a note in the "post migration cleanup" ticket.

2024-12-19 22:44 UTC, stephenfuqua commented on docs/getting-started/edfi-exchange/technology/student-survey-dashboard-for-teachers.md
> +You can try out Project Buzz by visiting [buzz-demo.ed-fi.org](http://buzz-demo.ed-fi.org).  
We need to remove this entirely. Again, not required today, since we also have it out in Confluence.

2024-12-19 22:44 UTC, stephenfuqua approved these changes

2024-12-19 22:44 UTC, merged