[DOC-104] Import Ed-Fi ODS/API Suite 3 v7.2
Ed-Fi-Alliance-OSS/ed-fi-alliance-oss.github.io pull request #42
Opened 2024-10-24 04:08 UTC by chrisgocode

2024-10-24 19:32 UTC, chrisgocode commented on docs/reference/2-ods-api/img/identities2.PNG
Will need to add these files again. Using this as a reminder for myself.

2024-10-27 22:53 UTC, stephenfuqua reviewed
Wow, that's a lot of images. Please moves images to `/static/img/reference/ods-api`.

2024-10-27 22:53 UTC, stephenfuqua commented on docs/community/2-sdlc/code-contribution-guidelines/coding-standards/README.md
> +   ```cs
`csharp` is actually correct, not `cs`, for codeblocks. Though `cs` _might_ work.

2024-10-28 22:59 UTC, roberthunterjr reviewed
Thanks for your work here Chris. I've done my best to open each of the pages that were added to see if I could catch any dead links / etc. May have missed some but overall the content looks fine.

I think we should move these imgs into static for now and move into the static/img/reference/ods-api` folder, following the pattern present.

Once we decide on the where these will ultimately be served, we *should* be able to drop in replace the location of `static/img/reference/ods-api` with `https://cdn.from.some.com/reference/ods-api` where the relative paths are the same.

2024-10-28 22:59 UTC, roberthunterjr commented on docs/reference/2-ods-api/client-developers-guide/api-routes.md
> +    "lastSurname:" "Ortiz",
nit: change to "lastSurname":"Ortiz", to correct formatting.

2024-10-29 00:58 UTC, stephenfuqua requested changes
I will have additional updates via PR to this PR.

2024-11-01 00:16 UTC, roberthunterjr commented on docs/reference/2-ods-api/getting-started/source-code-installation/readme.md
> +```
```suggestion
```mermaid
flowchart LR
    model["APIModel.json"]
    metaed[MetaEd] --> model

    db[(EdFi_Ods_Empty)]

    metaed --> db
    views["Database Views"]
    db -.-> views

    gen[["Code Generators"]]

    model --> gen
    views --> gen

    gen --> generated["compiled C#, json, XML"]

    generated --> server["Ed-FI ODS/API service"]
```
```

2024-11-01 00:17 UTC, roberthunterjr commented on docs/reference/2-ods-api/getting-started/source-code-installation/readme.md
> +```
Seems like Docusaurus does not properly support the @directives for formatting the shapes and is causing a syntax error.

2024-11-01 00:28 UTC, roberthunterjr commented on docs/reference/2-ods-api/platform-dev-guide/features/readme.md
> +| Feature | Is Enabled by Default | Description |
Might be something we want to shorten.

2024-11-01 00:30 UTC, roberthunterjr commented on docs/reference/2-ods-api/platform-dev-guide/utilities/bulk-load-client-utility.md
> +```mermaid
May want to re-evaluate the readability of this diagram.

2024-11-01 00:32 UTC, roberthunterjr reviewed
Thank you for all of this hard work! Just a couple of suggestions/ comments and we should be ready to approve!

2024-11-04 18:02 UTC, stephenfuqua approved these changes

2024-11-04 18:03 UTC, merged