Partner page refactoring and content updates
Ed-Fi-Alliance-OSS/ed-fi-alliance-oss.github.io pull request #47
Opened 2024-11-04 18:30 UTC by stephenfuqua

2024-11-04 18:39 UTC, stephenfuqua commented on docs/partners/1-badging/applying-for-a-badge.md
This page was split in two sometime after the markdown export from Confluence. Now it is up to date with Confluence.

2024-11-04 18:39 UTC, stephenfuqua commented on docs/partners/1-badging/available-badges/ed-fi-api-consumer-badge.md
> +![Ed-Fi API Consumer Badge](/img/partners/badging/ed-fi-api-consumer-badge.webp)
I moved all of the images under `/static/img`.

2024-11-04 18:39 UTC, stephenfuqua commented on docs/partners/1-badging/badgeComponent.jsx
I refactored the badge page to use div rows/columns instead of a table, as previously done for Certification. In addition, a new experiment: each registry is now three files:

* data
* component
* mdx page

2024-11-05 03:13 UTC, chrisgocode commented on docs/partners/1-badging/badgeComponent.jsx
Awesome! I was thinking of a similar approach originally but decided to keep it all in one file for simplicity.

2024-11-05 03:54 UTC, chrisgocode requested changes
Just some small suggestions, but everything looks great. Really like the idea of splitting the registry into three files!

2024-11-06 16:03 UTC, stephenfuqua commented on docs/partners/1-badging/badgeComponent.jsx
> +    ));
I see both of the email addresses working here. For example:

![image](https://github.com/user-attachments/assets/93664c4d-084e-4cf2-a336-a8fd9e05c0ba)

2024-11-06 16:11 UTC, stephenfuqua commented on docs/partners/1-badging/badgeData.js
> +      verifyingAgencies: ['Indiana DoE<br />Nebraska DoE'],
Good catch; I meant to remove that.

2024-11-06 16:33 UTC, stephenfuqua commented on docs/partners/2-certification/certificationComponent.jsx
> +            </a>
There is a subtle reason for it originally, but I think you're right that it would be better to see what we can do to have a similar design.

Done

2024-11-06 17:51 UTC, chrisgocode approved these changes

2024-11-06 18:17 UTC, merged